name: Build Perl EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Perl environment
      uses: shogo82148/actions-setup-perl@v1
      with:
        distribution: 'strawberry' # Strawberry Perl comes with CPAN

    - name: Install Dependencies
      run: |
        cpanm --installdeps .
        cpanm PAR PAR::Dist PAR::Packer

    - name: Convert .pl to .exe
      run: |
        pp -M sub::Util -M Module::Runtime -o zap2xml.exe zap2xml2.pl

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zap2xml.exe
        path: zap2xml.exe