name: Build Perl EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Perl environment
      uses: shogo82148/actions-setup-perl@v1
      with:
        distribution: 'strawberry' # Strawberry Perl comes with CPAN
        #perl-version: '5.24'

    - name: Install Dependencies
      run: |
        cpanm --installdeps .
        cpanm PAR::Packer

    - name: Convert .pl to .exe
      run: |
        pp -M sub::Util -o zap2xml.exe zap2xml2.pl

	- name: Create GitHub Release
	  uses: softprops/action-gh-release@v2
	  with:
	    files: zap2xml.exe
		env:
			GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}